### ISSUE TITLE
How will TRC member participation be tracked in order to establish good standing?

### ISSUE THREAD

**Issue by zimeon** [IIIF/website#123]
The proposed TRC process relies upon active engagement of participants and a notion of participation-based good standing in order to be able to vote. We need a transparent and lightweight process for tracking participation and good standing status in order to implement this.

**Comment by glenrobson** [comment]
@azaroth42 we started the TRC with mirroring the w3c good standing process. How do they record good standing? Does it work and how much effort does it take to keep current?

**Comment by azaroth42** [comment]
It was up to the individual WGs to track however they felt like, I believe.  There are some remnants of the process (putting "present+" into IRC) but it was very loosely defined, leading to a lack of transparency.  Basically the chairs and staff contact could declare someone to be not in good standing, and the process to reverse it wasn't worth pursuing. Part of the reason it's no longer in the process.

I would propose the following:

* Google spreadsheet, that is read-only to the Community and Consortium members, and read-write to ex officio members.
* The chair of the meeting is responsible for ensuring that
  * those actually present are accurately recorded in the sheet as being present
  * those who sent regrets (by email, to a TRC list? or on an issue in GH for consistency?) are recorded as being present
  * those who commented on *at least two* issues over the previous month are recorded as present
  * those who submitted comments / votes on the previous call's issues after the call are recorded as present

Code could automatically determine the github accounts of everyone who commented in the past month on issues that are up for review, and assuming there is a well specified method of adding your comments/votes after the previous meeting, the same applies.

There would need to be a mapping of TRC members' github accounts to however they're tracked in the spreadsheet (probably by including the github account in the spreadsheet!)

**Comment by glenrobson** [comment]
I do wonder if the overhead of running a good standing register is worth it (and this may have been the w3c rational). If I remember the reasons for it were:

 * Stop people dropping in on issues they care about
 * Ensuring consistent participation 

The dropping in issue will hopefully be negated by the super-majority voting unless there is a group of people dropping in. The agenda will be set by the meeting chair. 

If the only requirement is to give apologies at the meeting and you miss a few meetings chances are you are going to fall behind discussions. Also if good standing only affects consortium and community members then TSG chairs, editors, tech coordinator and MD may be dropping in cold to issues. 

Could we not rely on engaged members turning up where they can and cope with the odd drop in? Or have a flat ' you must participate in three meetings before being able to vote'?

**Comment by zimeon** [comment]
Discussion on [2018-08-29 Technical Community Call](https://docs.google.com/document/d/1Rx-sUh2STNf6_GxRC1ghqsEuoj5LymRDsxi0_WpqCJ4/edit) - no voices opposed to preceding https://github.com/IIIF/website/issues/123#issuecomment-406143146

**Comment by zimeon** [comment]
TRC editing call, need to change:

> TRC members may participate either by attending TRC meetings, or by engaging asynchronously online before the meeting. Asynchronous participation may involve contributing to the discussion of issues or voting on items being reviewed, and must, at minimum, include giving regrets in advance of meetings the member cannot attend. If a consortium or community member of the TRC does not participate for three consecutive meetings, either by attending or asynchronously, then they are not in “good standing” and cannot vote on issues until they have participated for three consecutive meetings. Standing will be tracked in a view-only spreadsheet. This requirement is ensure continued engagement, rather than dropping in for the occasional issue of interest without understanding the context in which the decision needs to be made. For this reason, TRC members must register their opinions directly and proxies are not allowed.

to reflect https://github.com/IIIF/website/issues/123#issuecomment-406143146 . Proxies comment can now be entirely removed

**Comment by zimeon** [comment]
Change to:

> TRC members participate by contributing to the discussion of issues and voting on items being reviewed, via the GitHub issue tracker, either synchronously during the meeting or asynchronously. If a consortium or community member of the TRC does not participate over the timeframe of three consecutive meetings, then they are not in “good standing” and cannot vote on issues until they have participated for three consecutive meetings. Standing will be tracked by analysis of participation on the GitHub issue tracker. This requirement is to ensure continued engagement, rather than dropping in for the occasional issue of interest without understanding the context in which the decision needs to be made.

**Comment by zimeon** [comment]
Changes above were made Sep 2018 and TRC is up and running. Closing
