### ISSUE TITLE
Add CoCo, IIIF-C Exec and Operating Committee memberships to the website

### ISSUE THREAD

**Issue by zimeon** [IIIF/website#129]
I think these should all be easily findable from http://iiif.io/community/consortium/

It has come up in discussion of the TRC proposal that community members do not know quite what CoCo is (description buried in MOU) and certainly not who the current member are. We should be more transparent and make the function and membership of these groups easy to find and understand.

**Comment by hadro** [comment]
We now have Exec and OpCom on the website (though I need to update the membership on those): https://iiif.io/community/consortium/consortium_committees/

And when #593 is merged, we'll have a CoCo page on the site also

**Comment by hadro** [comment]
This is now all done
