### ISSUE TITLE
Add intranda to participating institutions

### ISSUE THREAD

**Issue by janvonde** [IIIF/website#174]
intranda GmbH is the main developer of the open source software [Goobi workflow](https://github.com/intranda/goobi) and [Goobi viewer](https://github.com/intranda/goobi-viewer-core). The Goobi viewer implements the IIIF image and the IIIF presentation APIs. 

It would be great if the name `intranda GmbH` and the website `https://goobi.io` could be added to the participating institutions section of the community page of the website.

**Comment by glenrobson** [comment]
Hi,

You should be listed now at:

https://iiif.io/community/#participating-institutions

Cheers

Glen
