### ISSUE TITLE
Broken link to the list of tests of the Image API validator

### ISSUE THREAD

**Issue by regisrob** [IIIF/website#184]
Just noticed that the following link is broken on the Image API Validator "Instruction/Get Test Image" page (https://iiif.io/api/image/validator/download/): https://iiif.io/api/image/validator/service/list_tests (returns a weird auth page)

cc @glenrobson

**Comment by glenrobson** [comment]
This is a really strange one, I tried to find out which level this issue occurred at (proxy layer, api website or image validator). After testing it appeared to happen at the proxy layer, no requests were getting to the image validator. 

Running the proxy locally didn't recreate the issue so it must be something on the AWS proxy instance. After some googling I wondered if the IP address nginx was using for `http://image-validator.iiif.io`  had got stale and it was proxying someone else's machine. 

The login page mentioned above seems to be for an older version of the following software:

https://www.workfront.com/

called attask.com. To see if this was the issue I upped the logging on the proxy and ran a restart. Unfortunately that has fixed the problem so its no longer possible to see why it happened. I will close this issue for now but wanted to document the steps in case it re-occurs.
