### ISSUE TITLE
Add Image and Presentation 3.0 BETA links to https://iiif.io/technical-details/

### ISSUE THREAD

**Issue by zimeon** [IIIF/website#258]
... so that people can find the beta specs easily

**Comment by hadro** [comment]
@glenrobson Could you take a look at this next week? It's a good suggestion, but I'm not sure of the best way to handle, and curious to know from you if there's a good model for pointing to beta releases in the past

**Comment by glenrobson** [comment]
How does the following look:

https://iiif.io/technical-details/

**Comment by zimeon** [comment]
Looks good to me. I'd say close, done.

**Comment by glenrobson** [comment]
Great thanks
