### ISSUE TITLE
Preview branches showing up in Google results

### ISSUE THREAD

**Issue by hadro** [IIIF/website#263]
As I was looking for old newsletter items, I'm seeing preview branches for the website appear in Google results. That can't be good. 
Anything we can do to prevent that?

**Comment by jpstroop** [comment]
Oof. If they're broken/no longer available, some kind of catch-all redirect can probably be put in place.

Should we be sharing out previews at all? I've never been quite sure.

**Comment by hadro** [comment]
Evidence, in case it's useful in diagnosing: https://www.google.com/search?safe=off&hl=en&ei=gDIaXcmVIaH45gL63baQCA&q=iiif+preview&oq=iiif+preview&gs_l=psy-ab.3...7073.7457..7681...0.0..0.94.180.2......0....1..gws-wiz.2ueHu_pgst4

**Comment by azaroth42** [comment]
Or just search: inurl:preview.iiif.io

Can we put in a robots.txt for preview.iiif.io to block crawlers?

**Comment by hadro** [comment]
Just looping back to some old tickets we can hopefully clear out -- @glenrobson, did you adjust robots.txt or something else to tackle this? Seems to be better now, and the search Rob linked to no longer shows preview branches so hopefully we can close this up as done

**Comment by glenrobson** [comment]
Yes I added a robots.txt: https://preview.iiif.io/robots.txt
