### ISSUE TITLE
Update Editorial process

### ISSUE THREAD

**Issue by azaroth42** [IIIF/website#312]
@IIIF/editors ...

Minor editorial update:

> * A link to the branch (i.e. http://mybranch.iiif.io) must be included ...

This should use the "new" syntax for previews.

Process update:

* We should include the TRC approval for normative issues into the described process.

Process update:

* We haven't done 4 meetings a year for the last couple of years. I think we should drop it to three, with two required. And add the possibility of a virtual face to face like we did this year.

**Comment by zimeon** [comment]
All three proposed changes are good by me

**Comment by azaroth42** [comment]
One more:

The 4th bullet under 2.3 says that there must be at least one editorial :+1: on any change for the website.  When we had one repo this made sense, but now that it is split between website and api, Mike and I think the change is to limit the need for an editorial thumbs-up to just /api/

**Comment by zimeon** [comment]
I agree that we should restrict the editorial :+1: to `/api/` only.

This would still apply to things like the current [nokogiri fix](https://github.com/IIIF/api/pull/1887) where one editor and then Glen merging still seems fine. But having this apply everwhere puts too much reliance upon the editors to make progress and is beyond appropriate editorial scope.

**Comment by tomcrane** [comment]
Agree - approval relates to /api

**Comment by mikeapp** [comment]
👍
