### ISSUE TITLE
Use https version of Google Fonts

### ISSUE THREAD

**Issue by zimeon** [IIIF/website#35]
See old PR https://github.com/IIIF/api/pull/1178 with change to use https for Google fonts (we forgot to move it over earlier).

@mejackreed: it seems that as a website using external resources loaded in a user's browser (iiif.io), using the HTTPS protocol version of that resource is a responsible future proof choice.

@zimeon: 👍 Will be required for #11. I don't see a reason to delay going ahead with this but will wait for another opinion

**Comment by hadro** [comment]
With rollout of new site theme, closing this out at no longer relevant
