### ISSUE TITLE
add cantelope to apps and demos

### ISSUE THREAD

**Issue by srabun** [IIIF/website#36]

**Comment by imoutsatsos** [comment]
Adding my original comment from the Slack conversation. Please, note the correct name: Cantaloupe, not Cantelope ;-)

Reviewing the web site today, I was surprised to not find the Cantaloupe image server: https://medusa-project.github.io/cantaloupe/ on the list of iiif image servers http://iiif.io/apps-demos/#image-servers Could somebody please add this very capable and easy to setup server that many of us are using?

**Comment by glenrobson** [comment]
How does the following look:

http://preview.iiif.io/root/cantaloupe/apps-demos/#image-servers

**Comment by imoutsatsos** [comment]
Looks good. 
Small spelling mistake RE: 'Canataloupe supports' should read 'Cantaloupe supports..'

**Comment by glenrobson** [comment]
Thank you for spotting that. I've corrected it and deployed to live.
