### ISSUE TITLE
"Group info page" link wrong on Wireframe and beta

### ISSUE THREAD

**Issue by hadro** [IIIF/website#524]
Not sure why it's happening, but the "group info page" link on the event cards is broken for Wireframe and Beta -- it appears as the following:
Wireframe: `https://preview.iiif.io/root/wireframefunction%20link()%20%7B%20%20%20%20[native%20code]%7D` 
Beta: `https://beta.iiif.io/function%20link()%20%7B%20%20%20%20[native%20code]%7D`

It works fine locally, so I'm not sure what the issue is. Perhaps some variable that's in the deployment config?

**Comment by glenrobson** [comment]
Should be fixed now.
