### ISSUE TITLE
Missing images in Image 2.1 spec page

### ISSUE THREAD

**Issue by scossu** [IIIF/website#526]
The Image 2.1 spec page seems to have at least a couple of missing images, e.g. "Primary resource types" near https://iiif.io/api/presentation/2.1/#basic-types and "All resource types" near https://iiif.io/api/presentation/2.1/#22-additional-types

Additionally, I see some 404 redirect loops in my request console.

**Comment by hadro** [comment]
Thanks for the eagle eyes, @scossu! @glenrobson, this seems like it might be related to the webp conversion -- I thought we were only replacing links to pngs if the webp existed (which in this case it does not). Am I wrong?

**Comment by glenrobson** [comment]
Thanks @scossu I've fixed the 404 redirect loop. Ill look into the missing images now...

**Comment by glenrobson** [comment]
Yes it looks like its this line here:

```
{% include content/inline-image.html image="presentation/2.1/img/objects.png" alt_text="Primary Resource Types" caption="Primary Resource Types" float="right"%}
```

Which calls: https://github.com/IIIF/iiifc-theme/blob/main/_includes/content/inline-image.html

It doesn't check that the webp exists it just assumes it does. Can we create a webp version of these images?

**Comment by hadro** [comment]
This should be all fixed now! Thanks again for the heads up.
