### ISSUE TITLE
Reinstate copy-able anchors for headings in spec documents

### ISSUE THREAD

**Issue by azaroth42** [IIIF/website#529]
For example, https://iiif.io/api/presentation/3.0/#type works to take you to the definition of the `type` property, but it's not in the table of contents and the selectable link has disappeared in the new website.

It does work on hover for the main links:
![Screen Shot 2021-11-12 at 5 03 47 PM](https://user-images.githubusercontent.com/871868/141540185-718ce042-2b9d-41ac-a5d7-0f4c732765af.png)

But not for things like the property names in the specs:

![Screen Shot 2021-11-12 at 5 04 33 PM](https://user-images.githubusercontent.com/871868/141540224-a8e74dd0-e4e4-4e26-b9f2-e9435b2dcf27.png)

**Comment by hadro** [comment]
Thanks for the clarification, this is addressed in https://github.com/IIIF/api/pull/2078
I added hover through h5
Deployment example is here: https://preview.iiif.io/api/heading_anchor_fix/presentation/3.0/#type

**Comment by hadro** [comment]
This is deployed!
