### ISSUE TITLE
Add support for Twitter Cards and Open Graph 

### ISSUE THREAD

**Issue by leanderseige** [IIIF/website#586]
The iiif.io website does not provide meta tags for Open Graph or Twitter Cards yet. These meta tags allow social media platforms to create nice looking previews when users share links to web pages. I recommend adding support for these meta tags in the future:

first information may be found here: https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started or https://ogp.me/

Success can be verified with https://cards-dev.twitter.com/validator or https://www.opengraph.xyz/

**Comment by hadro** [comment]
Thanks, Leander -- first pass at this is in progress here: https://github.com/IIIF/website/pull/584
Though it's slightly complicated by the fact that we disallow * for robots.txt for the preview URLs generated, which blocks the validation... but we'll figure out a way to test and deploy.

**Comment by hadro** [comment]
Ok, this is done as a first-pass -- we have another task which is to move the functionality into the theme repo from the website repo, but at least for the main website basic open graph and Twitter card tags should be in place!
