### ISSUE TITLE
Coco - not on IIIF pages

### ISSUE THREAD

**Issue by glenrobson** [IIIF/website#592]
I can't seem to find any reference to Coco on the IIIF pages. Could we include the new charter where it is formed by group chairs?

**Comment by glenrobson** [comment]
I think this is the doc to convert: https://docs.google.com/document/d/1Y6mkZ2a4rbKCYpfdUvlHMLS7d329ex5vdze9yybYgfc/edit?usp=sharing

**Comment by hadro** [comment]
First pass of this is at #593

**Comment by hadro** [comment]
This is merged in
