### ISSUE TITLE
Proposal to add two vendors 

### ISSUE THREAD

**Issue by regisrob** [IIIF/website#635]
Here are two suggestions for [IIIF-Compliant Vendors and Software Providers](https://iiif.io/get-started/vendors/) (both in French):

- LIMB Gallery (i2S) https://www.i2s.fr ([details](https://www.i2s.fr/fr/numerisation-patrimoniale/solutions-logicielles-limb/limb-gallery))
- Ligéo Archives (Empreinte Digitale) https://www.ligeo-archives.com ([details](https://www.ligeo-archives.com/actualites/lire/de-nouveaux-venus-et-l-arrivee-de-monocle-votre-nouvelle-visionneuse/129/page:2/n:143))

**Comment by hadro** [comment]
Thanks, @regisrob! Will get these incorporated
